### ISSUE TITLE
Documentation implies data is pre-parsed

### ISSUE THREAD

**Issue by bane73** [pwarelis/Ajax-Typeahead#2]
The README implies that the JSON-data is automagically-parsed into a usable format by your code.

I think a note to remind the user that they need to somehow ensure the data is JS (not just JSON) is in order.

ie: when I set my data-source to a Java-method that returned a JSON-string, the data presented by your code split each individual letter of the string into a unique value -- so, "[ \"zoo\" ]" would render as 3 different suggestions: 'z', 'o', and 'o'.

To fix that I had to use your preProcess(data)-method and return $.parseJSON( data )

No big deal to fix that, and I imagine there are use-cases where 'fixing' this would break those -- just might help to augment the documentation.

**Comment by pwarelis** [comment]
The data is pre-parsed by jQuery. Internally I call $.ajax() on every request.
Check the raw response of your Java method, because it seems to me that you're
returning a string. I've tested this with objects and arrays, no problems.
The raw response for an array should be:

["Ajax","Ajax-Typeahead"]

Can you confirm that this is what you're receiving?

**Comment by bane73** [comment]
Paul, sorry for the delay in getting back to you -- I was on vacation over the weekend.

Sorry for this - you're right.  When I booted the machine this morning and removed the ref to $.parseJSON(data), it just worked.  I had definitely tried it originally without that and it wasn't working; guess I'm going to chalk it up to my IDE being out-of-sync or something since I rarely reboot or restart GF.

Thanks for the awesome code, yours is the better of the options I've seen and is very flexible.  
:)

**Comment by pwarelis** [comment]
Glad to hear it works for you Brandon.
You're welcome

**Comment by ghost** [comment]
Hey pwarelis, great added functionality that I'm trying to use.

I'm having the same issue bane73 was.

Eg. 
If I simply hard code a ajax reply from php as echo '["Ajax","Ajax-Typeahead"]'; or echo json_encode('["Ajax","Ajax-Typeahead"]');
What is returned becomes, ["Ajax","Ajax-Typeahead"]  or  "[\"Ajax\",\"Ajax-Typeahead\"]"

and every individual letter becomes a result item the way bane73 describes.

Doing my head in, not sure what I should be returning to get whole words :)

Thanks

**Comment by pwarelis** [comment]
``` php
header('Content-type: application/json');
echo json_encode(array("string1", "string2"));
exit;
```

**Comment by ghost** [comment]
ah, awesome

Thanks for your help
