### ISSUE TITLE
Script breaks regular bootstrap functionality

### ISSUE THREAD

**Issue by josebalius** [pwarelis/Ajax-Typeahead#4]
I installed this script on my application to use for on my fields, but I still needed the default bootstrap functionality which works off the source: property. Problem was that it stopped working after I installed this script.

I made a change to line 214:

From:

if (this.ajax.displayField) {

To:

if (typeof this.ajax != "undefined" && this.ajax.displayField) {

this.ajax seemed to be undefined and it was breaking the rest of the sorter function. Not sure if you want me to put in a pull request and fix it or if you can patch your code.

Apart from that, great job on the script!

**Comment by pwarelis** [comment]
Good catch Jose. Fixed.
